default: rogaluna-icon-file-b-8

dir: rogaluna-icon-file-b-2

txt: rogaluna-icon-file-b-7

jpg: rogaluna-icon-file-b-6
png: rogaluna-icon-file-b-6

mp3: rogaluna-icon-file-b-3
flac: rogaluna-icon-file-b-3

pdf: rogaluna-icon-file-b-14

docx: rogaluna-icon-file-b-1

xls: rogaluna-icon-file-b-5
xlsx: rogaluna-icon-file-b-5

zip: rogaluna-icon-file-b-4