default: xedia rogaluna-icon-file-b-8

dir: xedia rogaluna-icon-file-b-2

txt: xedia rogaluna-icon-file-b-7

jpg: xedia rogaluna-icon-file-b-6
png: xedia rogaluna-icon-file-b-6

pdf: xedia rogaluna-icon-file-b-14
