default: xedia rogaluna-icon-file-b-8

dir: xedia rogaluna-icon-file-b-2

txt: xedia rogaluna-icon-file-b-7

jpg: xedia rogaluna-icon-file-b-6
png: xedia rogaluna-icon-file-b-6

mp3: xedia rogaluna-icon-file-b-3
flac: xedia rogaluna-icon-file-b-3

pdf: xedia rogaluna-icon-file-b-14

docx: xedia rogaluna-icon-file-b-1

xls: xedia rogaluna-icon-file-b-5
xlsx: xedia rogaluna-icon-file-b-5

zip: xedia rogaluna-icon-file-b-4